CREATE TABLE "USER_AGENCY" (
  "auto_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id" char(6) UNIQUE NOT NULL DEFAULT '',
  "agency_name" varchar(100) NOT NULL DEFAULT '',
  "owner_name" varchar(100) NOT NULL DEFAULT '',
  "phone" char(10) NOT NULL DEFAULT '',
  "profile_photo_path" varchar(100),
  "tax_code" varchar(20),
  "address" varchar(255),
  "email" varchar(50) UNIQUE NOT NULL,
  "password_hash" char(64) NOT NULL
);

CREATE OR REPLACE FUNCTION set_custom_user_agency_id()
RETURNS TRIGGER AS $$
BEGIN
    NEW.id := 'UA' || LPAD(NEW.auto_id::text, 4, '0');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER set_user_agency_id
BEFORE INSERT ON "USER_AGENCY"
FOR EACH ROW
EXECUTE FUNCTION set_custom_user_agency_id();
DROP TRIGGER set_user_agency_id ON "USER_AGENCY";
DROP FUNCTION set_custom_user_agency_id;

CREATE TABLE inventory_product (
  "agency_id" char(6) NOT NULL,
  "product_id" char(6) NOT NULL,
  "quantity" int NOT NULL DEFAULT 0,
  "imported_timestamp" timestamp NOT NULL DEFAULT current_timestamp,
  "expired_date" date NOT NULL,
  "in_price" integer NOT NULL,
  PRIMARY KEY ("agency_id", "product_id", "imported_timestamp")
);

INSERT INTO "USER_AGENCY" (email, password_hash)
VALUES ('abcd', '123')
RETURNING auto_id, id;
SELECT * FROM "USER_AGENCY";
TRUNCATE "USER_AGENCY" RESTART IDENTITY;
DROP TABLE "USER_AGENCY";
