CREATE TABLE sales_invoice (
  "auto_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id" char(6) UNIQUE NOT NULL,
  "agency_id" char(6) NOT NULL,
  "recorded_at" timestamp NOT NULL DEFAULT current_timestamp,
  "customer_id" char(6) NOT NULL,
  "total_payment" int NOT NULL DEFAULT 0
);

CREATE TABLE invoice_product (
  "agency_id" char(6) NOT NULL,
  "invoice_id" char(6) NOT NULL,
  "product_id" char(6),
  "quantity" int NOT NULL,
  "price" int NOT NULL,
  PRIMARY KEY ("agency_id", "invoice_id", "product_id")
);

CREATE OR REPLACE FUNCTION set_custom_sales_invoice_id()
RETURNS TRIGGER AS $$
BEGIN
    NEW.id := 'SI' || LPAD(NEW.auto_id::text, 4, '0');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER set_sales_invoice_id
BEFORE INSERT ON sales_invoice
FOR EACH ROW
EXECUTE FUNCTION set_custom_sales_invoice_id();